<?php

namespace Database\Seeders;

use App\Models\Producto;
use App\Models\Categoria;
use App\Models\Laboratorio;
use Illuminate\Database\Seeder;

class ProductosSeeder extends Seeder
{
    public function run(): void
    {
        $categorias = Categoria::all();
        $laboratorios = Laboratorio::all();

        $productos = [
            [
                'codigo_interno' => 'IBUP-500',
                'codigo_barra' => '7798156202157',
                'nombre' => 'Ibupirac 500mg',
                'principio_activo' => 'Ibuprofeno',
                'forma_farmaceutica' => 'Comprimido',
                'concentracion' => '500mg',
                'laboratorio_id' => $laboratorios->random()->id,
                'unidad_medida' => 'comprimido',
                'tipo_receta' => 'ninguna',
                'es_controlado' => false,
                'stock_minimo' => 20,
                'stock_critico' => 10,
                'activo' => true,
            ],
            [
                'codigo_interno' => 'AMOX-500',
                'codigo_barra' => '7798156202158',
                'nombre' => 'Amoxicilina 500mg',
                'principio_activo' => 'Amoxicilina',
                'forma_farmaceutica' => 'Cápsula',
                'concentracion' => '500mg',
                'laboratorio_id' => $laboratorios->random()->id,
                'unidad_medida' => 'cápsula',
                'tipo_receta' => 'simple',
                'es_controlado' => false,
                'stock_minimo' => 15,
                'stock_critico' => 5,
                'activo' => true,
            ],
            [
                'codigo_interno' => 'PARA-500',
                'codigo_barra' => '7798156202159',
                'nombre' => 'Paracetamol 500mg',
                'principio_activo' => 'Paracetamol',
                'forma_farmaceutica' => 'Comprimido',
                'concentracion' => '500mg',
                'laboratorio_id' => $laboratorios->random()->id,
                'unidad_medida' => 'comprimido',
                'tipo_receta' => 'ninguna',
                'es_controlado' => false,
                'stock_minimo' => 30,
                'stock_critico' => 10,
                'activo' => true,
            ],
            [
                'codigo_interno' => 'DIAZ-5',
                'codigo_barra' => '7798156202160',
                'nombre' => 'Diazepam 5mg',
                'principio_activo' => 'Diazepam',
                'forma_farmaceutica' => 'Comprimido',
                'concentracion' => '5mg',
                'laboratorio_id' => $laboratorios->random()->id,
                'unidad_medida' => 'comprimido',
                'tipo_receta' => 'retenida',
                'es_controlado' => true,
                'registro_isp' => 'ISP-2024-001',
                'stock_minimo' => 5,
                'stock_critico' => 2,
                'activo' => true,
            ],
            [
                'codigo_interno' => 'OMEP-20',
                'codigo_barra' => '7798156202161',
                'nombre' => 'Omeprazol 20mg',
                'principio_activo' => 'Omeprazol',
                'forma_farmaceutica' => 'Cápsula',
                'concentracion' => '20mg',
                'laboratorio_id' => $laboratorios->random()->id,
                'unidad_medida' => 'cápsula',
                'tipo_receta' => 'ninguna',
                'es_controlado' => false,
                'stock_minimo' => 20,
                'stock_critico' => 8,
                'activo' => true,
            ],
            [
                'codigo_interno' => 'LOSA-50',
                'codigo_barra' => '7798156202162',
                'nombre' => 'Losartán 50mg',
                'principio_activo' => 'Losartán',
                'forma_farmaceutica' => 'Comprimido',
                'concentracion' => '50mg',
                'laboratorio_id' => $laboratorios->random()->id,
                'unidad_medida' => 'comprimido',
                'tipo_receta' => 'simple',
                'es_controlado' => false,
                'stock_minimo' => 20,
                'stock_critico' => 8,
                'activo' => true,
            ],
            [
                'codigo_interno' => 'ENAL-10',
                'codigo_barra' => '7798156202163',
                'nombre' => 'Enalapril 10mg',
                'principio_activo' => 'Enalapril',
                'forma_farmaceutica' => 'Comprimido',
                'concentracion' => '10mg',
                'laboratorio_id' => $laboratorios->random()->id,
                'unidad_medida' => 'comprimido',
                'tipo_receta' => 'simple',
                'es_controlado' => false,
                'stock_minimo' => 15,
                'stock_critico' => 5,
                'activo' => true,
            ],
            [
                'codigo_interno' => 'ATOR-20',
                'codigo_barra' => '7798156202164',
                'nombre' => 'Atorvastatina 20mg',
                'principio_activo' => 'Atorvastatina',
                'forma_farmaceutica' => 'Comprimido',
                'concentracion' => '20mg',
                'laboratorio_id' => $laboratorios->random()->id,
                'unidad_medida' => 'comprimido',
                'tipo_receta' => 'simple',
                'es_controlado' => false,
                'stock_minimo' => 15,
                'stock_critico' => 5,
                'activo' => true,
            ],
            [
                'codigo_interno' => 'METF-850',
                'codigo_barra' => '7798156202165',
                'nombre' => 'Metformina 850mg',
                'principio_activo' => 'Metformina',
                'forma_farmaceutica' => 'Comprimido',
                'concentracion' => '850mg',
                'laboratorio_id' => $laboratorios->random()->id,
                'unidad_medida' => 'comprimido',
                'tipo_receta' => 'simple',
                'es_controlado' => false,
                'stock_minimo' => 25,
                'stock_critico' => 10,
                'activo' => true,
            ],
            [
                'codigo_interno' => 'LORA-10',
                'codigo_barra' => '7798156202166',
                'nombre' => 'Loratadina 10mg',
                'principio_activo' => 'Loratadina',
                'forma_farmaceutica' => 'Comprimido',
                'concentracion' => '10mg',
                'laboratorio_id' => $laboratorios->random()->id,
                'unidad_medida' => 'comprimido',
                'tipo_receta' => 'ninguna',
                'es_controlado' => false,
                'stock_minimo' => 20,
                'stock_critico' => 8,
                'activo' => true,
            ],
            [
                'codigo_interno' => 'CETA-10',
                'codigo_barra' => '7798156202167',
                'nombre' => 'Cetirizina 10mg',
                'principio_activo' => 'Cetirizina',
                'forma_farmaceutica' => 'Comprimido',
                'concentracion' => '10mg',
                'laboratorio_id' => $laboratorios->random()->id,
                'unidad_medida' => 'comprimido',
                'tipo_receta' => 'ninguna',
                'es_controlado' => false,
                'stock_minimo' => 20,
                'stock_critico' => 8,
                'activo' => true,
            ],
            [
                'codigo_interno' => 'CLON-0.5',
                'codigo_barra' => '7798156202168',
                'nombre' => 'Clonazepam 0.5mg',
                'principio_activo' => 'Clonazepam',
                'forma_farmaceutica' => 'Comprimido',
                'concentracion' => '0.5mg',
                'laboratorio_id' => $laboratorios->random()->id,
                'unidad_medida' => 'comprimido',
                'tipo_receta' => 'retenida',
                'es_controlado' => true,
                'registro_isp' => 'ISP-2024-002',
                'stock_minimo' => 5,
                'stock_critico' => 2,
                'activo' => true,
            ],
            [
                'codigo_interno' => 'KETO-100',
                'codigo_barra' => '7798156202169',
                'nombre' => 'Ketoprofeno 100mg',
                'principio_activo' => 'Ketoprofeno',
                'forma_farmaceutica' => 'Comprimido',
                'concentracion' => '100mg',
                'laboratorio_id' => $laboratorios->random()->id,
                'unidad_medida' => 'comprimido',
                'tipo_receta' => 'simple',
                'es_controlado' => false,
                'stock_minimo' => 15,
                'stock_critico' => 5,
                'activo' => true,
            ],
            [
                'codigo_interno' => 'DICL-50',
                'codigo_barra' => '7798156202170',
                'nombre' => 'Diclofenaco 50mg',
                'principio_activo' => 'Diclofenaco',
                'forma_farmaceutica' => 'Comprimido',
                'concentracion' => '50mg',
                'laboratorio_id' => $laboratorios->random()->id,
                'unidad_medida' => 'comprimido',
                'tipo_receta' => 'simple',
                'es_controlado' => false,
                'stock_minimo' => 20,
                'stock_critico' => 8,
                'activo' => true,
            ],
            [
                'codigo_interno' => 'AZIT-500',
                'codigo_barra' => '7798156202171',
                'nombre' => 'Azitromicina 500mg',
                'principio_activo' => 'Azitromicina',
                'forma_farmaceutica' => 'Comprimido',
                'concentracion' => '500mg',
                'laboratorio_id' => $laboratorios->random()->id,
                'unidad_medida' => 'comprimido',
                'tipo_receta' => 'simple',
                'es_controlado' => false,
                'stock_minimo' => 10,
                'stock_critico' => 4,
                'activo' => true,
            ],
            [
                'codigo_interno' => 'CEFA-500',
                'codigo_barra' => '7798156202172',
                'nombre' => 'Cefalexina 500mg',
                'principio_activo' => 'Cefalexina',
                'forma_farmaceutica' => 'Cápsula',
                'concentracion' => '500mg',
                'laboratorio_id' => $laboratorios->random()->id,
                'unidad_medida' => 'cápsula',
                'tipo_receta' => 'simple',
                'es_controlado' => false,
                'stock_minimo' => 10,
                'stock_critico' => 4,
                'activo' => true,
            ],
            [
                'codigo_interno' => 'SALB-100',
                'codigo_barra' => '7798156202173',
                'nombre' => 'Salbutamol 100mcg',
                'principio_activo' => 'Salbutamol',
                'forma_farmaceutica' => 'Aerosol',
                'concentracion' => '100mcg/dosis',
                'laboratorio_id' => $laboratorios->random()->id,
                'unidad_medida' => 'inhalador',
                'tipo_receta' => 'simple',
                'es_controlado' => false,
                'stock_minimo' => 10,
                'stock_critico' => 4,
                'activo' => true,
            ],
            [
                'codigo_interno' => 'BUDES-200',
                'codigo_barra' => '7798156202174',
                'nombre' => 'Budesonida 200mcg',
                'principio_activo' => 'Budesonida',
                'forma_farmaceutica' => 'Aerosol',
                'concentracion' => '200mcg/dosis',
                'laboratorio_id' => $laboratorios->random()->id,
                'unidad_medida' => 'inhalador',
                'tipo_receta' => 'simple',
                'es_controlado' => false,
                'stock_minimo' => 8,
                'stock_critico' => 3,
                'activo' => true,
            ],
            [
                'codigo_interno' => 'AMLO-5',
                'codigo_barra' => '7798156202175',
                'nombre' => 'Amlodipino 5mg',
                'principio_activo' => 'Amlodipino',
                'forma_farmaceutica' => 'Comprimido',
                'concentracion' => '5mg',
                'laboratorio_id' => $laboratorios->random()->id,
                'unidad_medida' => 'comprimido',
                'tipo_receta' => 'simple',
                'es_controlado' => false,
                'stock_minimo' => 20,
                'stock_critico' => 8,
                'activo' => true,
            ],
            [
                'codigo_interno' => 'LEVOT-100',
                'codigo_barra' => '7798156202176',
                'nombre' => 'Levotiroxina 100mcg',
                'principio_activo' => 'Levotiroxina',
                'forma_farmaceutica' => 'Comprimido',
                'concentracion' => '100mcg',
                'laboratorio_id' => $laboratorios->random()->id,
                'unidad_medida' => 'comprimido',
                'tipo_receta' => 'simple',
                'es_controlado' => false,
                'stock_minimo' => 15,
                'stock_critico' => 5,
                'activo' => true,
            ],
            [
                'codigo_interno' => 'PRED-20',
                'codigo_barra' => '7798156202177',
                'nombre' => 'Prednisona 20mg',
                'principio_activo' => 'Prednisona',
                'forma_farmaceutica' => 'Comprimido',
                'concentracion' => '20mg',
                'laboratorio_id' => $laboratorios->random()->id,
                'unidad_medida' => 'comprimido',
                'tipo_receta' => 'simple',
                'es_controlado' => false,
                'stock_minimo' => 10,
                'stock_critico' => 4,
                'activo' => true,
            ],
            [
                'codigo_interno' => 'METO-1000',
                'codigo_barra' => '7798156202178',
                'nombre' => 'Metformina 1000mg',
                'principio_activo' => 'Metformina',
                'forma_farmaceutica' => 'Comprimido',
                'concentracion' => '1000mg',
                'laboratorio_id' => $laboratorios->random()->id,
                'unidad_medida' => 'comprimido',
                'tipo_receta' => 'simple',
                'es_controlado' => false,
                'stock_minimo' => 20,
                'stock_critico' => 8,
                'activo' => true,
            ],
            [
                'codigo_interno' => 'HIDR-25',
                'codigo_barra' => '7798156202179',
                'nombre' => 'Hidroclorotiazida 25mg',
                'principio_activo' => 'Hidroclorotiazida',
                'forma_farmaceutica' => 'Comprimido',
                'concentracion' => '25mg',
                'laboratorio_id' => $laboratorios->random()->id,
                'unidad_medida' => 'comprimido',
                'tipo_receta' => 'simple',
                'es_controlado' => false,
                'stock_minimo' => 15,
                'stock_critico' => 5,
                'activo' => true,
            ],
            [
                'codigo_interno' => 'SERTR-50',
                'codigo_barra' => '7798156202180',
                'nombre' => 'Sertralina 50mg',
                'principio_activo' => 'Sertralina',
                'forma_farmaceutica' => 'Comprimido',
                'concentracion' => '50mg',
                'laboratorio_id' => $laboratorios->random()->id,
                'unidad_medida' => 'comprimido',
                'tipo_receta' => 'simple',
                'es_controlado' => false,
                'stock_minimo' => 10,
                'stock_critico' => 4,
                'activo' => true,
            ],
            [
                'codigo_interno' => 'TRAMA-50',
                'codigo_barra' => '7798156202181',
                'nombre' => 'Tramadol 50mg',
                'principio_activo' => 'Tramadol',
                'forma_farmaceutica' => 'Cápsula',
                'concentracion' => '50mg',
                'laboratorio_id' => $laboratorios->random()->id,
                'unidad_medida' => 'cápsula',
                'tipo_receta' => 'retenida',
                'es_controlado' => true,
                'registro_isp' => 'ISP-2024-003',
                'stock_minimo' => 5,
                'stock_critico' => 2,
                'activo' => true,
            ],
            [
                'codigo_interno' => 'ACET-600',
                'codigo_barra' => '7798156202182',
                'nombre' => 'Acetilcisteína 600mg',
                'principio_activo' => 'Acetilcisteína',
                'forma_farmaceutica' => 'Granulado',
                'concentracion' => '600mg',
                'laboratorio_id' => $laboratorios->random()->id,
                'unidad_medida' => 'sobre',
                'tipo_receta' => 'ninguna',
                'es_controlado' => false,
                'stock_minimo' => 10,
                'stock_critico' => 4,
                'activo' => true,
            ],
            [
                'codigo_interno' => 'AMBRO-30',
                'codigo_barra' => '7798156202183',
                'nombre' => 'Ambroxol 30mg',
                'principio_activo' => 'Ambroxol',
                'forma_farmaceutica' => 'Jarabe',
                'concentracion' => '30mg/5ml',
                'laboratorio_id' => $laboratorios->random()->id,
                'unidad_medida' => 'frasco',
                'tipo_receta' => 'ninguna',
                'es_controlado' => false,
                'stock_minimo' => 10,
                'stock_critico' => 4,
                'activo' => true,
            ],
            [
                'codigo_interno' => 'AMOX-SUS',
                'codigo_barra' => '7798156202184',
                'nombre' => 'Amoxicilina Suspensión',
                'principio_activo' => 'Amoxicilina',
                'forma_farmaceutica' => 'Suspensión oral',
                'concentracion' => '250mg/5ml',
                'laboratorio_id' => $laboratorios->random()->id,
                'unidad_medida' => 'frasco',
                'tipo_receta' => 'simple',
                'es_controlado' => false,
                'stock_minimo' => 10,
                'stock_critico' => 4,
                'activo' => true,
            ],
            [
                'codigo_interno' => 'DICL-GEL',
                'codigo_barra' => '7798156202185',
                'nombre' => 'Diclofenaco Gel 1%',
                'principio_activo' => 'Diclofenaco',
                'forma_farmaceutica' => 'Gel',
                'concentracion' => '1%',
                'laboratorio_id' => $laboratorios->random()->id,
                'unidad_medida' => 'tubo',
                'tipo_receta' => 'ninguna',
                'es_controlado' => false,
                'stock_minimo' => 10,
                'stock_critico' => 4,
                'activo' => true,
            ],
            [
                'codigo_interno' => 'CLOTR-CRE',
                'codigo_barra' => '7798156202186',
                'nombre' => 'Clotrimazol Crema 1%',
                'principio_activo' => 'Clotrimazol',
                'forma_farmaceutica' => 'Crema',
                'concentracion' => '1%',
                'laboratorio_id' => $laboratorios->random()->id,
                'unidad_medida' => 'tubo',
                'tipo_receta' => 'ninguna',
                'es_controlado' => false,
                'stock_minimo' => 10,
                'stock_critico' => 4,
                'activo' => true,
            ],
            [
                'codigo_interno' => 'MUPI-CRE',
                'codigo_barra' => '7798156202187',
                'nombre' => 'Mupirocina 2%',
                'principio_activo' => 'Mupirocina',
                'forma_farmaceutica' => 'Ungüento',
                'concentracion' => '2%',
                'laboratorio_id' => $laboratorios->random()->id,
                'unidad_medida' => 'tubo',
                'tipo_receta' => 'simple',
                'es_controlado' => false,
                'stock_minimo' => 8,
                'stock_critico' => 3,
                'activo' => true,
            ],
            [
                'codigo_interno' => 'INSU-RAP',
                'codigo_barra' => '7798156202188',
                'nombre' => 'Insulina rápida',
                'principio_activo' => 'Insulina humana',
                'forma_farmaceutica' => 'Solución inyectable',
                'concentracion' => '100UI/ml',
                'laboratorio_id' => $laboratorios->random()->id,
                'unidad_medida' => 'frasco',
                'tipo_receta' => 'simple',
                'es_controlado' => false,
                'stock_minimo' => 5,
                'stock_critico' => 2,
                'activo' => true,
            ],
            [
                'codigo_interno' => 'SALBU-JAR',
                'codigo_barra' => '7798156202189',
                'nombre' => 'Salbutamol Jarabe',
                'principio_activo' => 'Salbutamol',
                'forma_farmaceutica' => 'Jarabe',
                'concentracion' => '2mg/5ml',
                'laboratorio_id' => $laboratorios->random()->id,
                'unidad_medida' => 'frasco',
                'tipo_receta' => 'simple',
                'es_controlado' => false,
                'stock_minimo' => 10,
                'stock_critico' => 4,
                'activo' => true,
            ],
        ];

        foreach ($productos as $producto) {
            $producto['categoria_id'] = $categorias->random()->id;

            Producto::create($producto);
        }
    }
}